# -*- coding: utf-8 -*-
"""Program_Tubes_Kelompok_A (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUVNanCwlIOdmQUjjsYemiYwSjrxCacK

# Analisa COVID Nasional
"""

import requests
resp = requests.get('https://data.covid19.go.id/public/api/update.json')
print (resp)

cov_id_raw = resp.json()

print('Length of cov_id_raw : %d.' %len(cov_id_raw))
print('Komponen cov_id_raw  : %s.' %cov_id_raw.keys())
cov_id_update = cov_id_raw['update']

print('Tanggal pembaharuan data penambahan kasus :', cov_id_update['penambahan']['tanggal'])
print('Jumlah penambahan kasus positif :', cov_id_update['penambahan']['jumlah_positif'])
print('Jumlah penambahan kasus sembuh :', cov_id_update['penambahan']['jumlah_sembuh'])
print('Jumlah penambahan kasus meninggal :', cov_id_update['penambahan']['jumlah_meninggal'])
print('Jumlah total kasus positif hingga saat ini :', cov_id_update['total']['jumlah_positif'])
print('Jumlah total kasus sembuh hingga saat ini:', cov_id_update['total']['jumlah_sembuh'])
print('Jumlah total kasus meninggal hingga saat ini:', cov_id_update['total']['jumlah_meninggal'])

import requests
resp_kaltim = requests.get('https://data.covid19.go.id/public/api/prov_detail_KALIMANTAN_TIMUR.json')
resp_kalteng = requests.get('https://data.covid19.go.id/public/api/prov_detail_KALIMANTAN_TENGAH.json')
resp_kalbar = requests.get('https://data.covid19.go.id/public/api/prov_detail_KALIMANTAN_BARAT.json')
resp_kalsel = requests.get('https://data.covid19.go.id/public/api/prov_detail_KALIMANTAN_SELATAN.json')
resp_kaltara = requests.get('https://data.covid19.go.id/public/api/prov_detail_KALIMANTAN_UTARA.json')

cov_kaltim_raw = resp_kaltim.json()
cov_kalteng_raw = resp_kalteng.json()
cov_kalbar_raw = resp_kalbar.json()
cov_kalsel_raw = resp_kalsel.json()
cov_kaltara_raw = resp_kaltara.json()

"""# Analisa COVID Kaltim"""

from pandas.io.json import json_normalize
cov_kaltim_df = json_normalize(cov_kaltim_raw)
cov_kaltim_df

print('Nama-nama elemen utama:\n', cov_kaltim_raw.keys())
print('\nJumlah total kasus COVID-19 di Kalimantan Timur                 : %d' %cov_kaltim_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Kalimantan Timur         : %f.2%%' %cov_kaltim_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Kalimantan Timur : %f.2%%' %cov_kaltim_raw['sembuh_persen'])

import numpy as np
import pandas as pd
cov_kaltim = pd.DataFrame(cov_kaltim_raw['list_perkembangan'])
print('Info cov_kaltim:\n', cov_kaltim.info())
print('\nLima data teratas cov_kaltim:\n', cov_kaltim.head())

import pandas as pd 
import numpy as np

cov_kaltim_tidy = (cov_kaltim.drop(columns=[item for item in cov_kaltim.columns
if item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_kaltim_tidy['tanggal'] = pd.to_datetime(cov_kaltim_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_kaltim_tidy.head())

cov_kaltim_tidy['kasus_aktif'] = (cov_kaltim_tidy['akumulasi_kasus'])-(cov_kaltim_tidy['akumulasi_sembuh'])
cov_kaltim_tidy

from datetime import date

x = cov_kaltim_tidy['tanggal']
cov_kaltim_tidy['bulan'] = x.apply(lambda y: y.strftime("%b"))

cov_kaltim_tidy

cov_kaltim_tidy['bulan'] = pd.Categorical(cov_kaltim_tidy['bulan'],categories=['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],ordered=True)
cov_kaltim_tidy.sort_values('tanggal',ascending=True)

kaltim_grouped = cov_kaltim_tidy.groupby('bulan').sum()
kaltim_grouped

import matplotlib.pyplot as plt

kaltim_bar = kaltim_grouped.groupby(['bulan'])['kasus_baru'].sum()

kaltim_bar.plot.bar()

plt.savefig("kaltim_bar")

import matplotlib.pyplot as plt

plt.clf()
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(data=cov_kaltim_tidy, x='tanggal', height='kasus_baru')
plt.show()

"""# DOUBLE PLOT GRAFIK HARIAN DAN GRAFIK AKUMULATIF - PROV KALTIM"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates


data = cov_kaltim_tidy
x = data['tanggal']
y1 = data['kasus_baru']
y2 = data['akumulasi_kasus']

plt.clf()
fig, ax1 = plt.subplots(figsize=(10,5))
plt.title('Perbandingan Kasus Baru & Akumulasi Kasus', loc='center', pad=15, fontsize=20,)

color = 'tab:red'
ax1.set_xlabel('tanggal', fontsize=18)
ax1.set_ylabel('kasus_baru', color=color, fontsize=18)
ax1.plot(x, y1, color=color, linewidth=3)
ax1.tick_params(axis='y', labelcolor=color, labelsize=18)
ax1.tick_params(axis='x', labelsize=16)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('akumulasi_kasus [ribu]', color=color, fontsize=18)  # we already handled the x-label with ax1
ax2.plot(x, y2/1000, color=color, linewidth=4)
ax2.tick_params(axis='y', labelcolor=color, labelsize=18)
ax2.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.savefig('perbandingan kasus baru & akumulasi kasus.jpg', quality=95, dpi=1000)
plt.show()

import matplotlib.pyplot as plt
import matplotlib.dates as mdates


data = cov_kaltim_tidy
x = data['tanggal']
y1 = data['kasus_baru']
y2 = data['kasus_aktif']

plt.clf()
fig, ax1 = plt.subplots(figsize=(10,5))
plt.title('Perbandingan Kasus Baru & Kasus Aktif', loc='center', pad=15, fontsize=20,)

color = 'tab:red'
ax1.set_xlabel('tanggal', fontsize=18)
ax1.set_ylabel('kasus_baru', color=color, fontsize=18)
ax1.plot(x, y1, color=color, linewidth=3)
ax1.tick_params(axis='y', labelcolor=color, labelsize=18)
ax1.tick_params(axis='x', labelsize=16)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('kasus_aktif [ribu]', color=color, fontsize=18)  # we already handled the x-label with ax1
ax2.plot(x, y2/1000, color=color, linewidth=4)
ax2.tick_params(axis='y', labelcolor=color, labelsize=18)
ax2.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.savefig('perbandingan kasus baru & kasus aktif.jpg', quality=95, dpi=1000)
plt.show()

import matplotlib.pyplot as plt
import matplotlib.dates as mdates


data = cov_kaltim_tidy
x = data['tanggal']
y1 = data['sembuh']
y2 = data['akumulasi_sembuh']

plt.clf()
fig, ax1 = plt.subplots(figsize=(10,5))
plt.title('Perbandingan Kasus Sembuh & Akumulasi Sembuh', loc='center', pad=15, fontsize=20,)

color = 'tab:green'
ax1.set_xlabel('tanggal', fontsize=18)
ax1.set_ylabel('sembuh', color=color, fontsize=18)
ax1.plot(x, y1, color=color, linewidth=3)
ax1.tick_params(axis='y', labelcolor=color, labelsize=18)
ax1.tick_params(axis='x', labelsize=16)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('akumulasi_sembuh [ribu]', color=color, fontsize=18)  # we already handled the x-label with ax1
ax2.plot(x, y2/1000, color=color, linewidth=4)
ax2.tick_params(axis='y', labelcolor=color, labelsize=18)
ax2.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.savefig('perbandingan kasus sembuh & akumulasi sembuh.jpg', quality=95, dpi=1000)
plt.show()

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Pemisalan
data = cov_kaltim_tidy
x = data['tanggal']
y1 = data['meninggal']
y2 = data['akumulasi_meninggal']

plt.clf()
fig, ax1 = plt.subplots(figsize=(10,5))
plt.title('Perbandingan Kasus Meninggal & Akumulasi Meninggal', loc='center', pad=15, fontsize=20,)

color = 'tab:grey'
ax1.set_xlabel('tanggal', fontsize=18)
ax1.set_ylabel('meninggal', color=color, fontsize=18)
ax1.plot(x, y1, color=color, linewidth=3)
ax1.tick_params(axis='y', labelcolor=color, labelsize=18)
ax1.tick_params(axis='y', labelsize=16)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('akumulasi_meninggal [ribu]', color=color, fontsize=18)  # we already handled the x-label with ax1
ax2.plot(x, y2/1000, color=color, linewidth=3)
ax2.tick_params(axis='y', labelcolor=color, labelsize=18)
ax2.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))

plt.grid(axis='y')
plt.savefig('perbandingan kasus meninggal & akumulasi meninggal.jpg', quality=95, dpi=1000)
plt.show()

"""# PROV KALTENG"""

print('Nama-nama elemen utama:\n', cov_kalteng_raw.keys())
print('\nJumlah total kasus COVID-19 di Kalimantan Tengah                 : %d' %cov_kalteng_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Kalimantan Tengah         : %f.2%%' %cov_kalteng_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Kalimantan Tengah : %f.2%%' %cov_kalteng_raw['sembuh_persen'])

import numpy as np
import pandas as pd
cov_kalteng = pd.DataFrame(cov_kalteng_raw['list_perkembangan'])
print('Info cov_kalteng:\n', cov_kalteng.info())
print('\nLima data teratas cov_kalteng:\n', cov_kalteng.head())

cov_kalteng_tidy = (cov_kalteng.drop(columns=[item for item in cov_kalteng.columns
if item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_kalteng_tidy['tanggal'] = pd.to_datetime(cov_kalteng_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_kalteng_tidy.head())

from datetime import date

x = cov_kalteng_tidy['tanggal']
cov_kalteng_tidy['bulan'] = x.apply(lambda y: y.strftime("%b"))

cov_kalteng_tidy

cov_kalteng_tidy['bulan'] = pd.Categorical(cov_kalteng_tidy['bulan'],categories=['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],ordered=True)
cov_kalteng_tidy.sort_values('bulan',ascending=True)

kalteng_grouped = cov_kalteng_tidy.groupby('bulan').sum()
kalteng_grouped

import matplotlib.pyplot as plt

kalteng_bar = kalteng_grouped.groupby(['bulan'])['kasus_baru'].sum()

kalteng_bar.plot.bar()

"""# PROV KALSEL"""

print('Nama-nama elemen utama:\n', cov_kalsel_raw.keys())
print('\nJumlah total kasus COVID-19 di Kalimantan Selatan                 : %d' %cov_kalsel_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Kalimantan Selatan         : %f.2%%' %cov_kalsel_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Kalimantan Selatan : %f.2%%' %cov_kalsel_raw['sembuh_persen'])

import numpy as np
import pandas as pd
cov_kalsel = pd.DataFrame(cov_kalsel_raw['list_perkembangan'])
print('Info cov_kalsel:\n', cov_kalsel.info())
print('\nLima data teratas cov_kalsel:\n', cov_kalsel.head())

cov_kalsel_tidy = (cov_kalsel.drop(columns=[item for item in cov_kalsel.columns
if item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_kalsel_tidy['tanggal'] = pd.to_datetime(cov_kalsel_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_kalsel_tidy.head())

from datetime import date

x = cov_kalsel_tidy['tanggal']
cov_kalsel_tidy['bulan'] = x.apply(lambda y: y.strftime("%b"))

cov_kalsel_tidy

cov_kalsel_tidy['bulan'] = pd.Categorical(cov_kalsel_tidy['bulan'],categories=['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],ordered=True)
cov_kalsel_tidy.sort_values('bulan',ascending=True)

kalsel_grouped = cov_kalsel_tidy.groupby('bulan').sum()
kalsel_grouped

import matplotlib.pyplot as plt

kalsel_bar = kalsel_grouped.groupby(['bulan'])['kasus_baru'].sum()

kalsel_bar.plot.bar()

"""# PROV KALBAR"""

print('Nama-nama elemen utama:\n', cov_kalbar_raw.keys())
print('\nJumlah total kasus COVID-19 di Kalimantan Barat                 : %d' %cov_kalbar_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Kalimantan Barat         : %f.2%%' %cov_kalbar_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Kalimantan Barat : %f.2%%' %cov_kalbar_raw['sembuh_persen'])

import numpy as np
import pandas as pd
cov_kalbar = pd.DataFrame(cov_kalbar_raw['list_perkembangan'])
print('Info cov_kalbar:\n', cov_kalbar.info())
print('\nLima data teratas cov_kalbar:\n', cov_kalbar.head())

cov_kalbar_tidy = (cov_kalbar.drop(columns=[item for item in cov_kalbar.columns
if item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_kalbar_tidy['tanggal'] = pd.to_datetime(cov_kalbar_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_kalbar_tidy.head())

from datetime import date

x = cov_kalbar_tidy['tanggal']
cov_kalbar_tidy['bulan'] = x.apply(lambda y: y.strftime("%b"))

cov_kalbar_tidy

cov_kalbar_tidy['bulan'] = pd.Categorical(cov_kalbar_tidy['bulan'],categories=['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],ordered=True)
cov_kalbar_tidy.sort_values('bulan',ascending=True)

kalbar_grouped = cov_kalbar_tidy.groupby('bulan').sum()
kalbar_grouped

import matplotlib.pyplot as plt

kalbar_bar = kalbar_grouped.groupby(['bulan'])['kasus_baru'].sum()

kalbar_bar.plot.bar()

"""# PROV KALTARA"""

print('Nama-nama elemen utama:\n', cov_kaltara_raw.keys())
print('\nJumlah total kasus COVID-19 di Kalimantan Utara                 : %d' %cov_kaltara_raw['kasus_total'])
print('Persentase kematian akibat COVID-19 di Kalimantan Utara         : %f.2%%' %cov_kaltara_raw['meninggal_persen'])
print('Persentase tingkat kesembuhan dari COVID-19 di Kalimantan Utara : %f.2%%' %cov_kaltara_raw['sembuh_persen'])

import numpy as np
import pandas as pd
cov_kaltara = pd.DataFrame(cov_kaltara_raw['list_perkembangan'])
print('Info cov_kaltara:\n', cov_kalbar.info())
print('\nLima data teratas cov_kaltara:\n', cov_kaltara.head())

cov_kaltara_tidy = (cov_kaltara.drop(columns=[item for item in cov_kaltara.columns
if item.startswith('DIRAWAT')])
.rename(columns=str.lower)
.rename(columns={'kasus': 'kasus_baru'})
)
cov_kaltara_tidy['tanggal'] = pd.to_datetime(cov_kaltara_tidy['tanggal']*1e6, unit='ns')
print('Lima data teratas:\n', cov_kaltara_tidy.head())

from datetime import date

x = cov_kaltara_tidy['tanggal']
cov_kaltara_tidy['bulan'] = x.apply(lambda y: y.strftime("%b"))

cov_kaltara_tidy

cov_kaltara_tidy['bulan'] = pd.Categorical(cov_kaltara_tidy['bulan'],categories=['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],ordered=True)
cov_kaltara_tidy.sort_values('bulan',ascending=True)

kaltara_grouped = cov_kaltara_tidy.groupby('bulan').sum()
kaltara_grouped

import matplotlib.pyplot as plt

kaltara_bar = kaltara_grouped.groupby(['bulan'])['kasus_baru'].sum()

kaltara_bar.plot.bar()

"""# GRAFIK PERBANDINGAN"""

import matplotlib.pyplot as plt
gabung = pd.concat([kaltim_bar, kalteng_bar, kalbar_bar, kalsel_bar, kaltara_bar], axis=1)

gabung.plot.bar(figsize=(12,8), width=0.9)
plt.title('Perbandingan Kasus Positif tiap Provinsi', loc='center', pad=15, fontsize=20)

plt.xlabel('Bulan', fontsize=18)
plt.ylabel('Kasus Baru', fontsize=18)
plt.tick_params(axis='y',labelsize=18)
plt.tick_params(axis='x',labelsize=18)
plt.legend(["Kaltim", "Kalteng", "Kalbar", "Kalsel", "Kaltara"], shadow=True, title='Provinsi', loc='upper left', fontsize=17)
plt.grid(axis='y')
plt.savefig('perbandingan tiap provinsi.jpg', quality=95, dpi=1000)
plt.show()
